name: sleek
base: core18
version: '0.2.1'
summary: A simple todo manager based on the concept of todo.txt
description: |
  sleek is a simple todo manager based on the concept of todo.txt. That means you will use a simple but powerful syntax to add contexts and projects to your todos, you will prioritize them and set due dates. According to this input you will be able to filter and search your todos. There is no cloud integration, but as sleek writes your data to a plain text file, you can put it anywhere you want. That also means if you don't have sleek at hand or if you don't like it anymore you can just edit the todo.txt file with any text editor or other todo.txt application.

grade: stable
confinement: strict
icon: ./assets/icons/icon.png
license: MIT
compression: lzo
architectures:
- build-on: [amd64, armhf, arm64, i386, s390x, ppc64el]
apps:
  sleek:
    command: snap/command-chain/desktop-launch $SNAP/sleek/sleek --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
parts:
  sleek:
    plugin: nil
    build-environment:
    - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    build-snaps:
    - node/15/stable
    source: .
    override-build: |
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi
      npm install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/sleek
    stage-packages:
    - libnss3
    build-packages:
    - nodejs
    - npm
