name: sleek # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple todo manager based on the concept of todo.txt # 79 char long summary
description: |
  sleek is a simple todo manager based on the concept of todo.txt. That means you will use a simple but powerful syntax to add contexts and projects to your todos, you will prioritize them and set due dates. According to this input you will be able to filter and search your todos. There is no cloud integration, but as sleek writes your data to a plain text file, you can put it anywhere you want. That also means if you don't have sleek at hand or if you don't like it anymore you can just edit the todo.txt file with any text editor or other todo.txt application.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: ./assets/icons/icon.png
license: MIT
#architectures:
#  - build-on: [amd64, i386, arm64, s390x, ppc64el, armhf]
#    run-on: [amd64, i386, arm64, s390x, ppc64el, armhf]
#  - build-on: amd64
#    run-on: amd64
#apps:
#  sleek:
#    plugs:
#      - browser-support
#      - x11
#      - opengl
apps:
  sleek:
    command: desktop-launch "$SNAP/sleek/sleek" "--no-sandbox"
    plugs:
    - browser-support
    #- network
    #- network-bind
    - opengl
    #- pulseaudio
    - x11

parts:
  sleek:
    # See 'snapcraft plugins'
    #plugin: nil
    plugin: nodejs
    nodejs-package-manager: npm
    nodejs-version: 15.2.1
    build-snaps:
    - node/15/stable
    source: .
    override-build: |
        case $SNAPCRAFT_ARCH_TRIPLET in
          "i386-linux-gnu") ARCH="ia32";;
          "x86_64-linux-gnu") ARCH="x64";;
          "arm-linux-gnueabihf") ARCH="armv7l";;
          "aarch64-linux-gnu") ARCH="arm64";;
          *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
        esac
        npm install electron electron-packager &&
        ./node_modules/.bin/electron-packager ./dist --overwrite --platform=linux --arch=$ARCH --output=release-build --prune=true
        cp -v -R ./sleek-linux-$ARCH/ $SNAPCRAFT_PART_INSTALL/sleek
    stage-packages:
    - libasound2
    - libgconf-2-4
    - libnss3
    - libx11-xcb1
    - libxss1
    - libxtst6
    - libdrm2
    - libgbm1
    - libwayland-server0
    - libxcb-dri3-0
    - libatk-bridge2.0-0
    - libatk1.0-0
    - libatspi2.0-0
    - libavahi-client3
    - libavahi-common3
    - libcairo-gobject2
    - libcairo2
    - libcups2
    - libdatrie1
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libgdk-pixbuf2.0-0
    - libgraphite2-3
    - libgtk-3-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libpng16-16
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libxcb-render0
    - libxcb-shm0
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxfixes3
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1
    build-packages:
    - nodejs
    - npm
    - unzip

      # Adapted from snapcraft-desktop-helpers https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L183
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      #- libnss3
      #- libnspr4
      #- libxkbcommon0  # XKB_CONFIG_ROOT
      - fonts-liberation
      - ttf-dejavu-core
      #- gtk-common-themes
      #- ttf-ubuntu-font-family
      #- dmz-cursor-theme
      #- light-themes
      #- dark-themes
      #- adwaita-icon-theme
      #- gnome-themes-standard
      #- shared-mime-info
      #- libgtk2.0-0
      #- libgtk-3-0
      #- libgdk-pixbuf2.0-0
      #- libglib2.0-bin
      #- libgtk-3-bin
      #- unity-gtk3-module
      #- libappindicator3-1
      #- locales-all
      #- xdg-user-dirs
      #- ibus-gtk3
      #- libibus-1.0-5
