name: sleek
base: core18
version: '0.2.1'
summary: A simple todo manager based on the concept of todo.txt
description: |
  sleek is a simple todo manager based on the concept of todo.txt. That means you will use a simple but powerful syntax to add contexts and projects to your todos, you will prioritize them and set due dates. According to this input you will be able to filter and search your todos. There is no cloud integration, but as sleek writes your data to a plain text file, you can put it anywhere you want. That also means if you don't have sleek at hand or if you don't like it anymore you can just edit the todo.txt file with any text editor or other todo.txt application.

grade: stable
confinement: strict
icon: ./assets/icons/icon.png
license: MIT
architectures:
  - build-on: [amd64, arm64, s390x, ppc64el, armhf]
    run-on: [amd64, arm64, s390x, ppc64el, armhf]
apps:
  sleek:
    command: snap/command-chain/desktop-launch $SNAP/sleek/sleek --no-sandbox
    extensions: [gnome-3-28]
    plugs:
    - browser-support
parts:
  sleek:
    plugin: nodejs
    nodejs-package-manager: npm
    nodejs-version: 15.2.1
    build-snaps:
    - node/15/stable
    source: .
    override-build: |
      case $SNAPCRAFT_ARCH_TRIPLET in
        "i386-linux-gnu") ARCH="ia32";;
        "x86_64-linux-gnu") ARCH="x64";;
        "arm-linux-gnueabihf") ARCH="armv7l";;
        "aarch64-linux-gnu") ARCH="arm64";;
        *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
      esac
        npm install electron-packager
        ./node_modules/.bin/electron-packager . --overwrite --platform=linux --arch=$ARCH --output=release-build --prune=true
        cp -v -R ./sleek-linux-$ARCH $SNAPCRAFT_PART_INSTALL/sleek
    stage-packages:
    - libnss3
    build-packages:
    - nodejs
    - npm
